name: dapptools

on:
  pull_request:
    branches:
    - master
    
  schedule:
  - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Fetch submodules
      run: |
        git submodule init
        git submodule update --init --recursive

    - name: Install Nix
      run: curl -L https://nixos.org/nix/install | sh
  
    - name: Install dependencies
      run: npm install

    - name: Install and run dapptools
      env:
        ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
      run: |
        . $HOME/.nix-profile/etc/profile.d/nix.sh
        curl https://dapp.tools/install | sh
        nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions.solc_0_8_13
        pwd
        cat .dapprc
        DAPP_LINK_TEST_LIBRARIES=0 dapp test --rpc --rpc-block 13806816
